version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  fail_on_warning: false
  configuration: ./docs/source/conf.py
  
python:
  install:
    - method: pip
      path: .
    - requirements: ./docs/requirements.txt   

formats:
  - pdf
  - epub
