[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "git-gudder"
authors = [{name = "Cornelius-Figgle", email = "max@fullimage.net"}]
dynamic = ["version", "description"]
